name: Contribution 
description: Propose, discuss and make a contribution to the algorithmic art course
title: "[Algorithmic art contribution]: "
labels: ["contribution"]
body:
  - type: markdown
    attributes:
      value: |
        Describe a contribution you wish to make to the course, discuss it and perform it.
  - type: input
    id: contact
    attributes:
      label: Email address
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: tastk-type
    attributes:
      label: Task type
      description: What type of task are you proposing?
      options:
        - randomized piece
        - data-driven piece
        - advanced piece
        - exhibition piece
        - technical presentation
        - paper presentation
      default: 0
    validations:
      required: true
  - type: dropdown
    id: deadline
    attributes:
      label: Contribution's date
      description: Which week do you present your contribution?
      options:
        - week 2
        - week 4
        - week 5
        - week 6
        - week 7
        - week 8
        - week 11
        - week 12
        - week 13
        - week 14
        - exhibition
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the contribution you wish to propose (which programming language, which library, which inspiration, etc.)
    validations:
      required: true
